### ISSUE TITLE
Add ability to set configmap volumeLabel

### ISSUE THREAD

**Issue by cloudymax** [cloudymax/kubevirt-community-stack#31]
example:

```yaml
      volumes:
        - name: root-disk
          ephemeral:
            persistentVolumeClaim:
              claimName: test-windows-iso
        - name: user-data
          configMap:
            volumeLabel: "config-2"
            name: cloudbase-init
```
