### ISSUE TITLE
add options required to recreate working win10 vgpu instance

### ISSUE THREAD

**Issue by cloudymax** [cloudymax/kubevirt-community-stack#33]
working config:

```yaml
---
# Source: kubevirt-vm/templates/datavolume.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: win10-empty-cert
  namespace: windows10
data:
  ca.pem: ""
---
# Source: kubevirt-vm/templates/datavolume.yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: harddisk
  namespace: windows10
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: "true"
    volume.kubernetes.io/selected-node: scremlin
spec:
  source:
    pvc:
      namespace: windows10
      name: windows-install-rootdisk
  pvc:
    storageClassName:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 48Gi
---
# Source: kubevirt-vm/templates/virtualmachine.yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: windows
    metallb-service: win10
  namespace: windows10
  name: win10-ephemeral
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: win10-ephemeral
        kubevirt-service: win10-ephemeral
        kubevirt-manager.io/managed: "true"
    spec:
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        features:
          acpi: {}
          apic: {}
          hyperv:
            relaxed: {}
            vapic: {}
            vpindex: {}
            spinlocks:
              spinlocks: 8191
            synic: {}
            synictimer:
              direct: {}
            tlbflush: {}
            frequencies: {}
            reenlightenment: {}
            ipi: {}
            runtime: {}
            reset: {}
          kvm:
            hidden: false
          acpi: {}
          smm:
            enabled: true
        cpu:
          model: EPYC-Rome
          sockets: 1
          cores: 4
          threads: 2
        firmware:
          uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
          bootloader:
            efi:
              secureBoot: false
        devices:
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          autoattachPodInterface: true
          autoattachSerialConsole: false
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: false
          rng: {}
          gpus:
            - deviceName: nvidia.com/GRID_RTX6000-4Q
              name: gpu0
              virtualGPUOptions:
                display:
                  enabled: true
          inputs:
            - type: tablet
              bus: virtio
              name: tablet1
          disks:
            - name: windows-install-rootdisk
              disk:
                bus: virtio
              bootOrder: 1
        resources:
          limits:
            memory: 8Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 0
      priorityClassName: vm-standard
      volumes:
        - name: windows-install-rootdisk
          persistentVolumeClaim:
            claimName: harddisk
---
# Source: kubevirt-vm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: win10-ephemeral
  namespace: windows10
  labels:
    kubevirt.io/domain: win10-ephemeral
    kubevirt-manager.io/managed: "true"
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: vnc
      port: 5900
      targetPort: 5900
      protocol: TCP
    - name: rdp
      port: 3389
      targetPort: 3389
      protocol: TCP
    - name: sunshine0
      port: 47984
      targetPort: 47984
      protocol: TCP
    - name: sunshine1
      port: 47985
      targetPort: 47985
      protocol: TCP
    - name: sunshine2
      port: 47986
      targetPort: 47986
      protocol: TCP
    - name: sunshine3
      port: 47987
      targetPort: 47987
      protocol: TCP
    - name: sunshine4
      port: 47988
      targetPort: 47988
      protocol: TCP
    - name: sunshine5
      port: 47989
      targetPort: 47989
      protocol: TCP
    - name: sunshine6
      port: 47990
      targetPort: 47990
      protocol: TCP
    - name: sunshine7
      port: 47998
      targetPort: 47998
      protocol: UDP
    - name: sunshine8
      port: 47999
      targetPort: 47999
      protocol: UDP
    - name: sunshine9
      port: 48000
      targetPort: 48000
      protocol: UDP
    - name: sunshine10
      port: 48010
      targetPort: 48010
      protocol: TCP
  selector:
    kubevirt-service: win10-ephemeral
```
